### ISSUE TITLE
reuse_port not supported by socket module

### ISSUE THREAD

**Issue by kingUnique** [pyradius/pyrad#117]
Launching the async server on a windows machine, generates the following error

```
2019-11-11 17:22:50,956 [DEBUG   ] Using selector: SelectSelector
Error:  reuse_port not supported by socket module
Traceback (most recent call last):
  File "c:/Users/kiril.s/vsc-workspace/automation/sandbox/sb.py", line 95, in <module>
    server.initialize_transports(enable_auth=True, enable_acct=True)
  File "C:\Users\kiril.s\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 584, in run_until_complete
    return future.result()
  File "C:\Users\kiril.s\vsc-workspace\automation\.venv\lib\site-packages\pyrad\server_async.py", line 295, in initialize_transports
    loop=self.loop
  File "C:\Users\kiril.s\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 1223, in create_datagram_endpoint
    _set_reuseport(sock)
  File "C:\Users\kiril.s\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 90, in _set_reuseport
    raise ValueError('reuse_port not supported by socket module')
ValueError: reuse_port not supported by socket module
```

**Comment by nicolaspapp** [comment]
Hello, is there any plan to resolve this issue? Both sync and async versions of the pyrad server are not compatible with Windows

**Comment by anhmt90** [comment]
I got the same error on Windows 10, python 3.9.1520. Hope this will be fixed soon.

> Task exception was never retrieved
> future: <Task finished name='Task-1' coro=<start_server() done, defined at C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\asyncio\streams.py:58> exception=ValueError('reuse_port not supported by socket module')>
> Traceback (most recent call last):
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\asyncio\streams.py", line 94, in start_server
>     return await loop.create_server(factory, host, port, **kwds)
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 1481, in create_server
>     _set_reuseport(sock)
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 94, in _set_reuseport
>     raise ValueError('reuse_port not supported by socket module')
> ValueError: reuse_port not supported by socket module

**Comment by anhmt90** [comment]
I got the same error on Windows 10, python 3.9.1520. Hope this will be fixed soon.

```bash
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<start_server() done, defined at C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\asyncio\streams.py:58> exception=ValueError('reuse_port not supported by socket module')>
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\asyncio\streams.py", line 94, in start_server
    return await loop.create_server(factory, host, port, **kwds)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 1481, in create_server
    _set_reuseport(sock)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 94, in _set_reuseport
    raise ValueError('reuse_port not supported by socket module')
ValueError: reuse_port not supported by socket module
```
