### ISSUE TITLE
Cannnot send Status requests

### ISSUE THREAD

**Issue by alxgomz** [pyradius/pyrad#27]
Hello,

I am trying to use pyrad to build a tiny script to get statistics about my freeradus server. Freeradius server since version 2.x implements a "status server" that allow one to gather such statistcs using radius request (Status-Server). So I wrote the code bellow:

```
import pyrad.packet
from pyrad.client import Client
from pyrad.dictionary import Dictionary
dicts=Dictionary("/tmp/dictionaries")
srv=Client(server='localhost',authport=18121,secret='adminsecret',dict=dicts)
req=srv.CreatePacket(code=pyrad.packet.StatusServer)
req.AddAttribute("FreeRADIUS-Statistics-Type", "Authentication")
req.AddAttribute("Message-Authenticator", req.CreateAuthenticator())
reply=srv.SendPacket(req)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/pymodules/python2.7/pyrad/client.py", line 161, in SendPacket
    return self._SendPacket(pkt, self.acctport)
  File "/usr/lib/pymodules/python2.7/pyrad/client.py", line 123, in _SendPacket
    self._socket.sendto(pkt.RequestPacket(), (self.server, port))
AttributeError: Packet instance has no attribute 'RequestPacket'
```

If I try to use CreatAuthPacket instead, then freeradius complains about an invalid message-authenticator.

A similat request with radclient (which support status requests) works.

**Comment by GIC-de** [comment]
@l2isbad is this issue still open? 

It seems that freeRADIUS is expecting an authenticator with all bits set to zero?  This can be done as described below:

```
client = Client(server="localhost", secret=b"adminsecret", dict=Dictionary("/tmp/dictionaries"))
req = client.CreateAuthPacket(code=pyrad.packet.AccessRequest, authenticator=16 * six.b('\x00'))
req["FreeRADIUS-Statistics-Type"] = "Authentication"
reply = client.SendPacket(req)
```

I have not tested but should work. 

In general `CreateAuthPacket` is the right approach!

**Comment by alexs20** [comment]
Yes this issue is still open. It creates broken Status-Server request without Message-Authenticator.

**Comment by yishiashia** [comment]
Here is a status-server request example which is working for me:


```python
import pyrad.packet
from pyrad.client import Client
from pyrad.dictionary import Dictionary
import six
import hmac
import hashlib

dicts=Dictionary("/tmp/dictionaries")

srv=Client(server='localhost',secret='adminsecret',dict=dicts)

req=srv.CreateAuthPacket(code=pyrad.packet.StatusServer)

# 1. set the default Message-Authenticator as 16-bytes zero.
req["Message-Authenticator"] = 16*six.b("\x00")

# 2. get the raw packet binary
raw_packet = req.RequestPacket()

# 3. calculate the hmac-md5 with shared secret
digest = hmac.new('hello', raw_packet, hashlib.md5)

# 4. write back the Message-Authenticator
req["Message-Authenticator"] = digest.hexdigest().decode('hex')

reply=srv.SendPacket(req)
```

**Comment by GIC-de** [comment]
This should work with version 2.2 as shown below:

```
srv = Client(server="127.0.0.1", authport=18121, secret=b"foobar", dict=Dictionary("dictionary"))

req = srv.CreateAuthPacket(code=pyrad.packet.StatusServer)
req["FreeRADIUS-Statistics-Type"] = "All"
req.add_message_authenticator()
reply = srv.SendPacket(req)
```
